### ISSUE TITLE
The example project does not compile on Xcode 7.1

### ISSUE THREAD

**Issue by abbasmousavi** [processone/xmpp-messenger-ios#15]
@baoluo The example project (and the pod) does not compile on Xcode 7.1 (Compiles on XCode 7)

![screen shot 2015-10-26 at 4 31 32 pm](https://cloud.githubusercontent.com/assets/1249875/10729516/3a7166fe-7bff-11e5-9f73-2ebccc170741.png)

**Comment by baoluo** [comment]
I just updated to Xcode 7.1, and I can confirm this behaviour

**Comment by adozenlines** [comment]
Also had a few problems with the lib xml module mapping as well.

**Comment by baoluo** [comment]
I will compile the XMPPFramework against Xcode 7.1 to fix those errors

**Comment by baoluo** [comment]
Ok, two things about this error, the first one, I can pod spec lint without error. Secondly, if I use the XMPPFramework pod in a standalone app, it will compile. It's when it's embedded in xmpp-messenger-ios. I'll continue the investigation

**Comment by abbasmousavi** [comment]
@baoluo, XMPPFramework 3.6.6 pod compiles without errors on XCode 7.1.

**Comment by baoluo** [comment]
Ok I found the fix, I'll need to fix the XMPPFramework first, so I may include other changes before releasing a new pod for xmpp-messenger-ios

**Comment by baoluo** [comment]
I fixed the error in JSQMessageViewController https://github.com/jessesquires/JSQMessagesViewController/pull/1284

I will now do the same for the XMPPFramework

**Comment by baoluo** [comment]
In the meantime, you can just replace the non-modular import with the @import syntax

**Comment by baoluo** [comment]
I fixed the errors in the XMPPFramework, you can follow the pull request here https://github.com/robbiehanson/XMPPFramework/pull/614

**Comment by abbasmousavi** [comment]
@baoluo It seems that replacing non-modular import with the @import syntax does not solves the problem. 

![screen shot 2015-10-27 at 3 58 12 pm](https://cloud.githubusercontent.com/assets/1249875/10758031/e8ebe3f2-7cc3-11e5-9385-43d0f11c391a.png)
(Compiler errors after replace)

It seems that CocoaLumberJack can not be compiled as a module also.
Can you compile xmpp-ios-messenger without errors after replacing non-modular import with the @import syntax?

**Comment by baoluo** [comment]
Yes it's working fine. Maybe you can try to deep clean Xcode.

@import CocoaLumberJack;
@import CocoaAsyncSocket;

And don;t forget to remove the old imports :)

**Comment by adozenlines** [comment]
Failed to build - The link above reports this problem below but the Process One Project Builds
❌  /Users/travis/build/robbiehanson/XMPPFramework/Vendor/KissXML/DDXMLNode.h:6:9: module 'libxmlSimu' not found
@import libxmlSimu;

``` ^~~~~~~~~~
▸ Compiling XMPPMessage.m
❌  /Users/travis/build/robbiehanson/XMPPFramework/Vendor/KissXML/DDXMLNode.h:6:9: module 'libxmlSimu' not found

```

**Comment by abbasmousavi** [comment]
@baoluo I downloaded a fresh copy of this repository,  replaced import statements and deep cleaned XCode before compiling but still getting this error:

![screen shot 2015-10-28 at 1 07 42 pm](https://cloud.githubusercontent.com/assets/1249875/10784784/441fa57c-7d75-11e5-9167-e91e42824d43.png)

**Comment by baoluo** [comment]
@abbasmousavi , XMPPAnonymousAuthentication need to be changed as well ?

**Comment by abbasmousavi** [comment]
@baoluo  I don't think so, In another try I have changed .podspec file (this time without replacing import statements in xmpp and JSQMessagesViewController)

![screen shot 2015-10-28 at 2 13 02 pm](https://cloud.githubusercontent.com/assets/1249875/10786187/1acb2f94-7d7e-11e5-9257-f0682e36ccb4.png)

and now the import problem is gone but I get a new error: ".../Pods/XMPPFramework/Vendor/KissXML/DDXMLNode.h:4:9: Module 'libxml' not found
(see this: https://github.com/robbiehanson/XMPPFramework/issues/596)

May be there is no need to change import statement in other projects and fixing libxml problem will fix the issue?

**Comment by baoluo** [comment]
@abbasmousavi Yes because you are not importing the module map file for libxml now.

**Comment by abbasmousavi** [comment]
Yes, you are right.

**Comment by abbasmousavi** [comment]
@baoluo any new progress?

**Comment by baoluo** [comment]
I'm still waiting for JSQMessage and XMPPFramework to accept the pull request, but in the meantime you can manually fix the project by applying the modification

**Comment by abbasmousavi** [comment]
@baoluo  JSQMessage pull request is closed and as I said before, after applying the modifications I get another error that says Module "CocoaLumberJack" not found (in file XMPPLogging.h);

Could you please modify the example project in this repo so that it compiles with XCode 7.1?

**Comment by adozenlines** [comment]
The idea around open source is to allow the community to take part in the contribution of these projects. Fell free to make the change and submit your very own pull request to the respective repos.

Enjoy.

**Comment by baoluo** [comment]
@abbasmousavi changes have been committed to the example project, but like @adozenlines said, the best options would have that you made the changes I showed you, or more importantly, support my pull requests to the other third party libs. Because right now I fixed the example, but not the source.

**Comment by abbasmousavi** [comment]
@baoluo Thanks for changes (I didn't send PR because your proposed modifications didn't work on my project), finally I can compile my project, getting diff with your example project, I found that there was a strange permission issue on XMPPFramework folder in my project pods that caused "Module CocoaLumberJack not found" error. changing the permissions solved the problem.

Thanks again and I will support your PR on XMPP and  JSQMessage certainly.

**Comment by adozenlines** [comment]
I guess this can be closed.

**Comment by BrianHenryIE** [comment]
Thanks guys. I got stuck on the permission issue for a while and to fix it I deleted the `pods/XMPPFramework` folder and to recreate it ran `git clone https://github.com/robbiehanson/XMPPFramework.git`
Then I got it to build after implementing the changes in 
[JSQMessagesViewController #1284](https://github.com/robbiehanson/XMPPFramework/pull/614/files) and [XMPPFramework #614](https://github.com/jessesquires/JSQMessagesViewController/pull/1284/files).

**Comment by novinfard** [comment]
I got the same error on Xcode 7.1 and also it could not add xmpp_messenger_ios in app delegate (it cause unknown module error). Do you have complete project fix files?

**Comment by novinfard** [comment]
Also this error appears when direct example uses:
Use of unresolved identifier 'OneLastActivity'

**Comment by adozenlines** [comment]
Looks like the pods and sample are out of sync and the OneLastActivity is not part of project may be a merger gone bad.

**Comment by orkhanalizade** [comment]
@novinfard check have you in Pods the file "OneLastActivity.swift". If you do not have this file, add this manually and all will be fine.

**Comment by orkhanalizade** [comment]
@baoluo please, close this issue, because it works even in Xcode 7.2

**Comment by baoluo** [comment]
Ok @orkhanalizade, closing this now

**Comment by arunarya111** [comment]
@adozenlines how did you resolve this issue
Failed to build - The link above reports this problem below but the Process One Project Builds
❌ /Users/travis/build/robbiehanson/XMPPFramework/Vendor/KissXML/DDXMLNode.h:6:9: module 'libxmlSimu' not found
@import libxmlSimu;
i am facing the same after i installed xmpp seperately from github

**Comment by arunarya111** [comment]
@abbasmousavi how did you modify the permission to resolve cocoalumberjack not found issue

**Comment by baoluo** [comment]
@abbasmousavi , you have this error because the compiler doesn't find the custom import. Add it to your folder and the path un you Xcode's build settings
