### ISSUE TITLE
Hello, Problem While building this app! Need Help!

### ISSUE THREAD

**Issue by panfass** [processone/xmpp-messenger-ios#46]
Hello, 

Anyway, I am trying to build this xmpp application under Xcode 7.3.
I have this problem, I tried to google this issue and I still have not fixed this.

![2016-04os x 10 11 - vmware workstation 12 player non-commercial use only](https://cloud.githubusercontent.com/assets/16108478/14617576/ff3c849e-05ae-11e6-9c4c-9a8456e8e964.jpg)

Maybe its a problem of the newer Xcode 7.3? I am using El Capitan.
Maybe it is related to Pod base project?

Just to clarify, OneChat is under Pods Project. 
XMPPFramework already exists at build path, I added it manually.
Also setting "Allow Non-modular Includes in "Framework Modules" to YES under Build Setting didn't help.

Also, deep cleaning (with command+alt+shift+k) did not work! 

I followed the instuctions on this github page.
https://github.com/processone/xmpp-messenger-ios

Any advice please?

**Comment by pka23** [comment]
+1

**Comment by baoluo** [comment]
Hello @panfass, You have this problem because Xcode doesn't know how to build the framework. You can add the module.modulemap present in the pod to your target build settings (I'll push a patch on this soon)

**Comment by panfass** [comment]
![2016-04-19 14_48_44-os x 10 11 - vmware workstation 12 player non-commercial use only](https://cloud.githubusercontent.com/assets/16108478/14639679/321ca4ae-063e-11e6-968f-62e5ceceda13.jpg)

@baoluo I'm sorry but I am a little newbie. Is the setting here?
What should I write? I tried "XMPPFramework.modulemap" but no luck.Same Error!

![2016-04-19 14_47_18-os x 10 11 - vmware workstation 12 player non-commercial use only](https://cloud.githubusercontent.com/assets/16108478/14639750/7d2dcd74-063e-11e6-8d0d-3af2832f930c.jpg)

Thank you for your support!

**Comment by baoluo** [comment]
Ok @panfass , the file is within the pod folder (you can access it through Xcode or the finder), simply drag the file to the "header search path" in your target's build settings

**Comment by panfass** [comment]
Hello again @baoluo 

Unfortunately I cannot make it work still.

![2016-04-20 12_45_08-os x 10 11 - vmware workstation 12 player non-commercial use only](https://cloud.githubusercontent.com/assets/16108478/14672269/0f96de18-06f7-11e6-8953-e6122b45b5ee.jpg)
![2016-04-20 12_44_53-os x 10 11 - vmware workstation 12 player non-commercial use only](https://cloud.githubusercontent.com/assets/16108478/14672271/12d344ae-06f7-11e6-9af9-8a29da333d50.jpg)

I added all the .modulemap files I found under Target  Target Support files and also "module.modulemap" I found under XMPPFramework.

I then deep cleaned using command alt shift k. This message is still here!

![2016-04-20 12_56_39-os x 10 11 - vmware workstation 12 player non-commercial use only](https://cloud.githubusercontent.com/assets/16108478/14672313/5d57efe8-06f7-11e6-801d-bb380522582c.jpg)

Did I do anything wrong ? I looked to the other thread and saw that you are going to update this soon, but I am just curious of if I did anything wrong!

**Comment by capkin90** [comment]
I have the same problem. I added also the module.modulemap file to the "header search path".

**Comment by LOHITH1988** [comment]
Even iHave the same problems, Can any one help me to over come this

**Comment by panfass** [comment]
Actually I gave up on this. :/ Sorry!

**Comment by LOHITH1988** [comment]
Hi Im new to XMPP , I got a Chat application to do using swift can you
suggest me some basic tutorials  to follow don't have much idea about XMPP.

Thank you

**Comment by baoluo** [comment]
Hello @panfass , @capkin90, hello all, I'll update the pod/git repo so it will compile correctly on our machines, I need to figure it out why it's not working properly out of the box for you guys.

**Comment by ericxxp** [comment]
the same problem baoluo

**Comment by dezerta-cop** [comment]
same problem here too

**Comment by capkin90** [comment]
Hi baolou, thank you for the news. When we can expect with the update?

**Comment by detectedstealth** [comment]
@baoluo Same issue here just tried to follow the tutorial this morning.

**Comment by brod-ie** [comment]
@baoluo Any update on this?

**Comment by baoluo** [comment]
Hello guys !

I updated the Readme to reflect the changes you have to make !

Xcode 7.X compiler did change, and it doesn't like the modular import. 

The solution is to edit 3 files: replace the #import to @import as explained in the readme. 

I'll make a pull request to the owner of the XMPPFramework to include those changes so nobody will have to edit the file in the future.

Sorry for the inconvenience, I hope you'll build cool stuff ! 

Don't be afraid to contribute :)

**Comment by brod-ie** [comment]
Awesome cheers @baoluo

**Comment by brod-ie** [comment]
@baoluo As you kept the version the same in the podspec running `$ pod clean && pod install` doesn't fetch the latest changes, even installing directly (`pod 'xmpp-messenger-ios', :git => 'https://github.com/processone/xmpp-messenger-ios.git'`) doesn't seem to work. For now I've manually updated the source but am still getting the same errors:

```
/XMPPFramework/Core/XMPPStream.h:5:9: Include of non-modular header inside framework module 'XMPPFramework.XMPPStream'
/XMPPFramework/Core/XMPPLogging.h:62:9: Include of non-modular header inside framework module 'XMPPFramework.XMPPLogging'
/XMPPFramework/Core/XMPPLogging.h:62:9: Include of non-modular header inside framework module 'XMPPFramework.XMPPLogging'
```

**Comment by ericxxp** [comment]
Same as me @brod-ie :(

**Comment by baoluo** [comment]
Hello guys, as I wrote in the readme, the files have to be edited by hand, the problem is from the XMPPFramework, within the xmpp-messenger. So it needs to be updated before you can pod install without errors.

**Comment by brod-ie** [comment]
@baoluo My bad for not reading your message, I assumed as the issue was closed it was fixed (it was but with a caveat).

I think you should create a new issue for the above 3 errors and the manual steps to fix them. Until the PR for the XMPPFramework is accepted, there should be a corresponding issue here

**Comment by baoluo** [comment]
@brod-ie It's not a bad idea indeed, I'll do that !

**Comment by detectedstealth** [comment]
@baoluo Your updates to the read me do allow the project to compile. However there are other places in the readme which need to be updated to the latest swift syntax. Especially the cellForRowAtIndexPath's where you don't need the ! for the cell. (Xcode catches these luckily) 

Also in a few places xmpp-messenger-ios also needs to be updated as places on OneChat completely crash as the following when I try to get to the settings screen I get the following (maybe this is also a bug with the ReadMe guide somewhere?):

```
OneChat.swift line: 271
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=XMPPStreamErrorDomain Code=1 "Attempting to connect while already connected or connecting." UserInfo={NSLocalizedDescription=Attempting to connect while already connected or connecting.}
```

Looks like the try is not being handled correctly as when you use try! it will crash the app etc...

**Comment by baoluo** [comment]
Hello @detectedstealth Yes the code should be updated to remove all the force unwraps, I kept those for development purpose, "i wanted the crash to happen if something's not here" but for production it needs to be changed. If you want you can send a pull request.
